CC = gcc
#WARN_FLAGS = -Wall -Wextra -Werror

CFLAGS += -fPIC
# WARNING OPTIONS
# turn on typical warnings
CFLAGS += -Wall
CFLAGS += -Wextra
# turn warnings into errors
CFLAGS += -Werror

# suppress warnings for a couple of things
CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-missing-field-initializers
CFLAGS += -Wno-missing-braces

#CFLAGS += -fsanitize=address
CFLAGS += -fno-strict-aliasing
#CFLAGS += -fstack-protector-all

# TODO: re-enable this after some things are fixed, like SecurityKeys.h
CFLAGS += -Wno-ignored-qualifiers

# yet more warnings from https://news.ycombinator.com/item?id=7371806
CFLAGS += -Wformat=2
CFLAGS += -D_FORTIFY_SOURCE=2

WARN_FLAGS = ${CFLAGS}
FEATURES = splitdebug            
DEBUG_FLAGS = -g3 -ggdb3 -O2
C_STD = -std=gnu99
LIBS = -lcrypto -lcurl
DEFINES = 

WOLFLIBS = -I ./ -I/usr/local/include/wolfssl -I/usr/local/include/curl \
           -L/usr/local/lib -L/usr/local/include/wolfssl/wolfcrypt \
           -L/usr/local/include/wolfssl 
WOLFLIBS += -lcurl -lwolfssl
#WOLFLIBS += -fsanitize=address
#WOLFLIBS += -static-libasan
WOLFLIBS += -no-pie 
#WOLFLIBS += -Wl,-Bstatic 

vpath %.c ./ ./lib ./wolfssl_wrapper ./DRCode
SRC := $(wildcard *.c) \
       $(wildcard lib/*.c) \
       $(wildcard wolfssl_wrapper/*.c) \
       $(wildcard DRCode/*.c)
OBJS = $(SRC:%.c=%.o)

wolftest: DEFINES += -D __WOLF_SSL__ -D __KEYFACTOR_LOCAL_TESTING__ -D _DEBUG
wolftest: ${OBJS}
	gcc ${WARN_FLAGS} ${DEBUG_FLAGS} ${C_STD} ${DEFINES} -shared -o api_test $^ ${WOLFLIBS}

test: wolftest

# define the builds
%.o: %.c
	$(info building $@ from $<)
	- @${CC} ${DEFINES} ${WARN_FLAGS} ${DEBUG_FLAGS} ${C_STD} -c -o $@ $<

# define the clean or delete commands
.PHONY: deleteallobs
deleteallobs:
	rm -rf ${OBJS}
	rm -rf api_test

.PHONY: cleanall
cleanall: deleteallobs

.PHONY: clean
clean: deleteallobs
